apiVersion: v1
kind: Service
metadata:
  name: flask-job-runner-service
spec:
  type: NodePort
  selector:
    app: flask-job-runner
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31500
